name: iens
channels:
- defaults
- conda-forge
dependencies:
- google-api-python-client=1.6.4
- python=3.6.3
- scrapy=1.4.0
- jupyter=1.0.0
- pandas=0.21.0
- pandas-gbq=0.2.1
- jsonlines=1.2.0
- pip:
  - google-api-core==0.1.3
  - google-auth==1.2.1
  - google-auth-httplib2==0.0.3
  - google-auth-oauthlib==0.2.0
  - google-cloud-bigquery==0.28.0
  - google-cloud-core==0.28.0
  - google-resumable-media==0.3.1
  - googleapis-common-protos==1.5.3
